### ISSUE TITLE
Path should accept placeholder

### ISSUE THREAD

**Issue by laurentj** [backupchecker/backupchecker#10]
To do backup, I'm using Backup-manager : it generates files at regular interval, let's say each days. And it can keeps latest archives, for example 4 (and it erases olders). so I have

- myarchive-2015-02-23.tgz
- myarchive-2015-02-24.tgz
- myarchive-2015-02-25.tgz
- myarchive-2015-02-26.tgz

The problem is that we should indicate a fixed path into the path parameter. So backupchecker is not usable without renaming files etc...

So it should be useful to indicate placeholders in the path. Here for example:

```
path= /somewhere/myarchive-%Y%-%m%-%d%.tgz
path= /somewhere/%Y%/myarchive-%d%.tgz
```

Where %Y% is the year, %m% is the month, %d% is the day of the month. If backupchecker is executed each day by a cron, each days it could verify the latest generated archive.

We could imagine other placeholder (no idea for the moment).

**Comment by backupchecker** [comment]
Hi Laurent,

It's indeed something I thought about and it would be nice to offer placeholders. I'll think about it to offer a convenient way to use it in Backup Checker.

Thanks a lot,
Carl Chenet

**Comment by backupchecker** [comment]
[Release 1.5 now available](https://github.com/backupchecker/backupchecker/releases/tag/1.5) with support for the placeholders, thanks a lot for your contribution!
Moreover I'm finishing to write a blog post about how to use Backup Checker to verify Backup-manager backups. Will be released Tuesday on [my blog](http://carlchenet.com). Stay tuned :)
