### ISSUE TITLE
support for non-tar backups?

### ISSUE THREAD

**Issue by anarcat** [backupchecker/backupchecker#12]
there are a lot of backup systems out there: rdiff-backup, bup, attic, duplicity, bacula... how are we supposed to check the backups on those systems with backup-checker?

**Comment by backupchecker** [comment]
Hi,

Thanks for your interest in Backup Checker :) BC was primarily aiming to only cover archives (tar.gz, zip, gzip, bzip, lzma) and trees of files. Now Backup Checker is more and more mature, we are developing features to interconnect it with other systems (see #9 and #10 and #11). That's a start but we're looking forward improving BC links with some of the softwares you gave.

Regards,
Carl Chenet

**Comment by anarcat** [comment]
thanks for considering my request. how modular is BC anyways? how easy would such extensions be to implement?

i know that at least `bup` has a homegrown "tree checker" to compare trees. to test bup backups, they decompress the backups and compare them to the original tree using that tool (which is basically rsync).

how do you test rsync? you solve the [halting problem](https://en.wikipedia.org/wiki/Halting_problem) first. ;)

**Comment by backupchecker** [comment]
Quite frankly I don't know how easy it would be to interface BC with a backup tool. These days I'm having a look at the core of some backup tools. Some features have been requesteded in that way (see #10 and #11) and I work on these ones but I don't have yet choose a backup tool BC could work with. Buf it is a growing request, so I'm investigating.

**Comment by backupchecker** [comment]
I'm finishing to write a blog post about how to use Backup Checker to verify Backup-manager backups. Will be released Tuesday on [my blog](http://carlchenet.com). Stay tuned :)

**Comment by backupchecker** [comment]
Two howto are now available [on the official community page](http://www.backupchecker.com/community) to make Backup Checker works with Backup-manager and Rsnapshot.
