### ISSUE TITLE
[FeatureRequest] Be able to use a stream from stdin or external command

### ISSUE THREAD

**Issue by tst2005** [backupchecker/backupchecker#3]
Hello,

I play with huge encrypted backups on tape (LTO 5-6 more than 1TB per tape).
The goal is to able to use backupchecker on a tar stream (without using disk space).
The stream will be a on-the-fly decrypted tar directly read from tape made by an external command.

Regards,

**Comment by backupchecker** [comment]
That's an interesting feature request thanks, i'll have a look at how to modify backup checker in order to support tar stream.

Regards,
Carl Chenet

**Comment by backupchecker** [comment]
Hi,

While waiting for the next release, you can get the work in progress in the **tar-stream** branch of the backup checker repository. It's from now on possible to use Backup Checker the following way:

$ cat /tmp/tests.tar.gz | ./backupchecker.py -G -

This creates the configuration files tarstream.conf and tarstream.list describing the tarstream and what's inside. I guess if you want to use it with a tape device, you need to indicate the path to the tape device with something like:

$ cat /dev/st0 | ./backupchecker.py -G -

If you want to verify a tar stream, use the following command:

$ cat /tmp/tests.tar.gz | ./backupchecker.py -c /path/to/conf/and/list/files

or for a tape device:

$ cat /tmp/tests.tar.gz | ./backupchecker.py -c /path/to/conf/and/list/files

I don't own a tape device myself, so don't hesitate to give me a feedback about it. It's still a WiP, but i think the next release should be published in a few days.

Regards,
Carl Chenet

**Comment by backupchecker** [comment]
https://github.com/backupchecker/backupchecker/commit/f017c6a90a0ba9f9a708ca26973ec781f3021f28

**Comment by backupchecker** [comment]
now available in 1.2 release
