### ISSUE TITLE
File tree check fails on FreeBSD

### ISSUE THREAD

**Issue by martymac** [backupchecker/backupchecker#7]
Hi,

On FreeBSD-current, backupchecker reports errors when checking a file tree. Here is how to reproduce the problem :

% mkdir test && sudo chmod 777 test && sudo chown root:wheel test && cd test

% mkdir -p a/b/c/ ; touch a/b/c/foo ; echo aaa > a/b/c/foo ; backupchecker -GH a ; backupchecker -c a.conf

% cat a.conf
[main]
name=a
type=tree
path=/files/Down/test/a
files_list=/files/Down/test/a.list
sha512=958ae8eeea9fecb6d0fc636ab443eb6f90eecf6e368c43f52553b7332307fdd48586daf71a462c63e7047fc0c1108beba1100a32db589c1272a7841fd79eb926

% cat a.list
[files]
b| =3 uid|1001 gid|0 owner|martymac group|wheel mode|755 type|d
mtime|1425460756.808454
b/c| =3 uid|1001 gid|0 owner|martymac group|wheel mode|755 type|d
mtime|1425460756.8154535
b/c/foo| =4 uid|1001 gid|0 owner|martymac group|wheel mode|644 type|f
mtime|1425460756.8164525 md5|5c9597f3c8245907ea71a89d9d39d08e

% cat a.out
WARNING:root:3 files with unexpected owners while checking
/files/Down/test/a:
WARNING:root:b owner is root. Should have been martymac.
WARNING:root:b/c owner is root. Should have been martymac.
WARNING:root:b/c/foo owner is root. Should have been martymac.

**Comment by backupchecker** [comment]
Thanks a lot for your bug report. Just succeeded reproducing the bug with :

# mkdir test && chmod 2777 test && chown root:root test && cd test
$ mkdir -p a/b/c/ ; touch a/b/c/foo ; echo aaa > a/b/c/foo ; backupchecker -GH a ; backupchecker -c a.conf
$ cat a.out 
WARNING:root:3 files with unexpected owners while checking /home/chaica/progra/test/a:
WARNING:root:b owner is root. Should have been chaica.
WARNING:root:b/c owner is root. Should have been chaica.
WARNING:root:b/c/foo owner is root. Should have been chaica.

chmod 2777 test seems to trigger the issue. Investigating on that.

**Comment by backupchecker** [comment]
ok found the bug. I'll write a relevant functional test and commit the fix.

**Comment by martymac** [comment]
Great, thanks!
