### ISSUE TITLE
It should check the modification date of the archive

### ISSUE THREAD

**Issue by laurentj** [backupchecker/backupchecker#9]
A critical feature is missing IMHO : an option in the configuration file to check the validity of the modification date of the archive. At this time, backupchecker can say that the archive is ok (all its files are ok, its size is ok etc), but it's totally useless if the archive was generated 3 month ago, although the backup system is configured to create backups each days.

In the configuration, we could set for example

```
mtime | < 3days
```

It will check that the archive was not older than 3 days (In this example, the format of the duration may not be a standard, but of course, it should follow a standard if it is implemented).
So backup checker could warn about the fact that the archive is too old, and so the system administrator can know there is a problem in its backup system.

**Comment by backupchecker** [comment]
Hi Laurent,

That's a great idea, it seems indeed really useful. Thanks a lot. I'll try to find about a good and convenient way to add this feature (especially the authorized pattern for the date).

Regards,
Carl Chenet

**Comment by backupchecker** [comment]
This feature will be available soon, I'm finishing the last tests. Should be released at the start of this new week.

**Comment by backupchecker** [comment]
Version 1.4 released.

Now every generated .conf file defines the mtime of the archive and the new parameter outdated allows to define a duration starting from the mtime of the archive. When this duration is expired, backupchecker triggers a warning specifying that the archive is outdated.

See [Backup Checker Configuration parameters details on Readthedocs](http://backupchecker.readthedocs.org/en/latest/configure.html#understanding-the-parameters-of-the-list-of-files)
